sudo: required
services:
  - docker

before_install:
  - docker build -t  ssaammoo/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true ssaammoo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-346939214257"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  

